version: "3.7"

services:
  backend:
    container_name: myapp_backend
    restart: always
    build: ./server
    environment:
      - APP_ENV=development
      - APP_PORT=3000
    volumes:
      - ./server/src:/var/www/backend/src
      - ./server/test:/var/www/backend/test
    working_dir: /var/www/backend
    ports:
      - "3001:3001"
    links:
      - mysql
    depends_on:
      - mysql
    env_file: 
      - ./server/.env
  frontend:
    container_name: myapp_frontend
    restart: always
    build: ./client
    environment:
      - APP_ENV=development
      - APP_PORT=3000
    volumes:
      - ./client:/var/www/frontend
    working_dir: /var/www/frontend
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    env_file: 
      - ./client/.env
  mysql: # Example Service
    container_name: myapp_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=myapp
      - MYSQL_DATABASE=nestjs
    ports:
    - "3308:3306"
    volumes:
    - myapp_mysql_data:/var/lib/mysql
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

volumes:
  myapp_mysql_data:

networks:
  default:
    external:
      name: myapp
